// Generated by Framer (2797bee)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/9CuDrCZlmZXJeSPS9ath/ZudIQAIKiLuLvdQkyvYi/eVdMENQYa.js";
import * as sharedStyle from "https://framerusercontent.com/modules/1viLL0gE96O4gITMXtxw/qxeiBUUwCura0kfeBie0/LsQ6y5c2A.js";
const cycleOrder = ["MHL0vGey3", "aEnHsQ8TK"];
const serializationHash = "framer-IvM36";
const variantClassNames = {
    aEnHsQ8TK: "framer-v-16mayrc",
    MHL0vGey3: "framer-v-1moyker"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Lg: "MHL0vGey3",
    Sm: "aEnHsQ8TK"
};
const getProps = ({
    description,
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        JSMWQ5C2q: description ? ? props.JSMWQ5C2q ? ? "Description",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "MHL0vGey3",
        vxIeboVSW: title ? ? props.vxIeboVSW ? ? "Title"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        vxIeboVSW,
        JSMWQ5C2q,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "MHL0vGey3",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1moyker", className, classNames),
                    "data-framer-name": "Lg",
                    layoutDependency: layoutDependency,
                    layoutId: "MHL0vGey3",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        aEnHsQ8TK: {
                            "data-framer-name": "Sm"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-zdjqmc",
                                "data-styles-preset": "LsQ6y5c2A",
                                style: {
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, rgb(0, 0, 0)))"
                                },
                                children: "Clarity"
                            })
                        }),
                        className: "framer-7gky3w",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "FerYkWDOS",
                        style: {
                            "--extracted-r6o4lv": "var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, rgb(0, 0, 0))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: vxIeboVSW,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-121x2hs",
                                "data-styles-preset": "eVdMENQYa",
                                style: {
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-1e23e8ab-09bc-463f-a722-5892dbae21bf, rgba(0, 0, 0, 0.6)))"
                                },
                                children: "See your money clearly so you make smarter decisions."
                            })
                        }),
                        className: "framer-1ukwkgt",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "cPgLHGmDU",
                        style: {
                            "--extracted-r6o4lv": "var(--token-1e23e8ab-09bc-463f-a722-5892dbae21bf, rgba(0, 0, 0, 0.6))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: JSMWQ5C2q,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-IvM36.framer-w6y9hp, .framer-IvM36 .framer-w6y9hp { display: block; }", ".framer-IvM36.framer-1moyker { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; height: 176px; justify-content: space-between; overflow: visible; padding: 32px; position: relative; width: 290px; }", ".framer-IvM36 .framer-7gky3w, .framer-IvM36 .framer-1ukwkgt { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-IvM36.framer-v-16mayrc.framer-1moyker { gap: 24px; height: min-content; justify-content: flex-start; padding: 24px; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 176
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"aEnHsQ8TK":{"layout":["fixed","auto"]}}}
 * @framerVariables {"vxIeboVSW":"title","JSMWQ5C2q":"description"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerckip2RYUC = withCSS(Component, css, "framer-IvM36");
export default Framerckip2RYUC;
Framerckip2RYUC.displayName = "page-company/section-hero/value card";
Framerckip2RYUC.defaultProps = {
    height: 176,
    width: 290
};
addPropertyControls(Framerckip2RYUC, {
    variant: {
        options: ["MHL0vGey3", "aEnHsQ8TK"],
        optionTitles: ["Lg", "Sm"],
        title: "Variant",
        type: ControlType.Enum
    },
    vxIeboVSW: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    JSMWQ5C2q: {
        defaultValue: "Description",
        displayTextArea: false,
        title: "Description",
        type: ControlType.String
    }
});
addFonts(Framerckip2RYUC, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framerckip2RYUC",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"aEnHsQ8TK\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"vxIeboVSW\":\"title\",\"JSMWQ5C2q\":\"description\"}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "176",
                "framerIntrinsicWidth": "290"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ckip2RYUC.map