// Generated by Framer (f76946f)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;DM Mono-500", "GF;DM Mono-500italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "DM Mono",
        openType: true,
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/dmmono/v14/aFTR7PB1QTsUX8KYvumzIYGnbKX9Rlk.woff2",
        weight: "500"
    }, {
        family: "DM Mono",
        openType: true,
        source: "google",
        style: "italic",
        url: "https://fonts.gstatic.com/s/dmmono/v14/aFTT7PB1QTsUX8KYth-o9YetbYf4VllXuA.woff2",
        weight: "500"
    }]
}];
export const css = [".framer-Kcq4X .framer-styles-preset-5r7f4r:not(.rich-text-wrapper), .framer-Kcq4X .framer-styles-preset-5r7f4r.rich-text-wrapper p { --framer-font-family: \"DM Mono\", monospace; --framer-font-family-italic: \"DM Mono\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 13px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 100%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }"];
export const className = "framer-Kcq4X";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}