// Generated by Framer (629c622)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryCache as l,
    QueryEngine as i
} from "framer";
import {
    DatabaseCollection as a
} from "./Cqtsvocq1-0.js";
import {
    resolveRichText as r
} from "./Cqtsvocq1-1.js";
let o = {
        id: {
            isNullable: !1,
            type: t.String
        },
        iiclUOEmo: {
            isNullable: !0,
            type: t.String
        },
        m_6lzjIa7: {
            isNullable: !0,
            type: t.String
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        }
    },
    n = [],
    u = e => {
        let t = n[e];
        if (t) return t().then(e => e.default);
    },
    c = new i,
    m = new l(c),
    p = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./Cqtsvocq1-chunk-default-0.framercms", "https://framerusercontent.com/modules/BsivQXNYqtlN8WGZhWH2/2nMiHVXQ2N7hC0PuledE/Cqtsvocq1.js").href.replace("/modules/", "/cms/")],
                indexes: [],
                resolveRichText: r,
                resolveVectorSetItem: u,
                schema: o
            })
        },
        displayName: "Categories"
    };
export default p;
e(p, {
    iiclUOEmo: {
        defaultValue: "",
        title: "Title",
        type: t.String
    },
    m_6lzjIa7: {
        title: "Slug",
        type: t.String
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/Cqtsvocq1:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/Cqtsvocq1:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [l] = await m.get({
            from: {
                data: p,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "m_6lzjIa7",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .m_6lzjIa7;
    },
    async getRecordIdBySlug(e, t) {
        let [l] = await m.get({
            from: {
                data: p,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "m_6lzjIa7",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerCollectionId": "Cqtsvocq1",
                "framerContractVersion": "1",
                "framerRecordIdKey": "id",
                "framerColorSyntax": "false",
                "framerData": "",
                "framerSlug": "m_6lzjIa7",
                "framerCollectionUtils": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerAutoSizeImages": "true"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}