// Generated by Framer (9e04080)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-R9lOn .framer-styles-preset-1vpoaom:not(.rich-text-wrapper), .framer-R9lOn .framer-styles-preset-1vpoaom.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, #000000); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-1e23e8ab-09bc-463f-a722-5892dbae21bf, rgba(0, 0, 0, 0.6)); --framer-link-text-decoration: none; transition: color 0.2s cubic-bezier(0.44, 0, 0.56, 1) 0s; }"];
export const className = "framer-R9lOn";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}