// Generated by Framer (2797bee)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/43x4xZtZ411NBehWnukJ/EhaCrSLj5FfVBgUSQ6dh/fXUOopoWI.js";
import * as sharedStyle from "https://framerusercontent.com/modules/6ws8DOBUTc9DZVjFiWda/xXaWTvMncu1E8vlh7e3m/MtiXJ4Kbr.js";
import Divider from "https://framerusercontent.com/modules/3j3j9UH1kbp7OWNvfYEG/oEeQ8lA3UnQM9H2akHVf/sfjV8PIJg.js";
import TransactionRow from "https://framerusercontent.com/modules/f5tA8VJxpZaksKY0J8l4/0C9durMopugygDj5uEM1/up6iy1_SU.js";
const TransactionRowFonts = getFonts(TransactionRow);
const DividerFonts = getFonts(Divider);
const cycleOrder = ["D7Zfd9aKU", "m2NDNoCf5"];
const serializationHash = "framer-unIje";
const variantClassNames = {
    D7Zfd9aKU: "framer-v-68izr1",
    m2NDNoCf5: "framer-v-iwtn14"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const addImageAlt = (image, alt) => {
    if (!image || typeof image !== "object") {
        return;
    }
    return { ...image,
        alt
    };
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Desktop/Tablet": "D7Zfd9aKU",
    Phone: "m2NDNoCf5"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "D7Zfd9aKU"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "D7Zfd9aKU",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-68izr1", className, classNames),
                    "data-framer-name": "Desktop/Tablet",
                    layoutDependency: layoutDependency,
                    layoutId: "D7Zfd9aKU",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        m2NDNoCf5: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-ly1p4h",
                                "data-styles-preset": "MtiXJ4Kbr",
                                style: {
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-456f6a7d-95db-4e28-a3b1-384de1e19e19, rgb(255, 255, 255)))"
                                },
                                children: "Filter by category & time"
                            })
                        }),
                        className: "framer-1vo8ve9",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "LvhSsuFzU",
                        style: {
                            "--extracted-r6o4lv": "var(--token-456f6a7d-95db-4e28-a3b1-384de1e19e19, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            m2NDNoCf5: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1dzuak8",
                                        "data-styles-preset": "fXUOopoWI",
                                        style: {
                                            "--framer-text-alignment": "left",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-456f6a7d-95db-4e28-a3b1-384de1e19e19, rgb(255, 255, 255)))"
                                        },
                                        children: "Filter by category & time"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-4znly9",
                        "data-framer-name": "list",
                        layoutDependency: layoutDependency,
                        layoutId: "UP7ZUbyCZ",
                        children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 76,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 0,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 0
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1p5z3an-container",
                                layoutDependency: layoutDependency,
                                layoutId: "Ff3_9qbMf-container",
                                nodeId: "Ff3_9qbMf",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(TransactionRow, {
                                    FZkmj7Zu4: "Ea6t1s6og",
                                    height: "100%",
                                    id: "Ff3_9qbMf",
                                    kegb7UkZq: "-$6.80",
                                    layoutId: "Ff3_9qbMf",
                                    nDbpvVAET: "Food & Drinks",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "Br9c1tVCd",
                                    width: "100%",
                                    XFV53Cjx9: "Starbucks",
                                    zvO3HzvYM: "May 22",
                                    ...addPropertyOverrides({
                                        m2NDNoCf5: {
                                            variant: "rML7zaR9u"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 1,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 100,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 92
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-16kjcov-container",
                                layoutDependency: layoutDependency,
                                layoutId: "AkYUWHCA_-container",
                                nodeId: "AkYUWHCA_",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(Divider, {
                                    fW4v8VMWk: "var(--token-9ae23472-2c52-4a18-9208-a0603db295c2, rgba(255, 255, 255, 0.08))",
                                    height: "100%",
                                    id: "AkYUWHCA_",
                                    layoutId: "AkYUWHCA_",
                                    style: {
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 76,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 125,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 109
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-vxg9l5-container",
                                layoutDependency: layoutDependency,
                                layoutId: "dX95hh9Yi-container",
                                nodeId: "dX95hh9Yi",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(TransactionRow, {
                                    FZkmj7Zu4: "Ea6t1s6og",
                                    height: "100%",
                                    id: "dX95hh9Yi",
                                    kegb7UkZq: "-$13.99",
                                    layoutId: "dX95hh9Yi",
                                    MNWfWU2ao: addImageAlt({
                                        pixelHeight: 40,
                                        pixelWidth: 40,
                                        src: "https://framerusercontent.com/images/4gfdDQz35VFKpiODG30B4PJbwM.png"
                                    }, ""),
                                    nDbpvVAET: "Entertainment",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "Br9c1tVCd",
                                    width: "100%",
                                    XFV53Cjx9: "Netflix",
                                    zvO3HzvYM: "May 19",
                                    ...addPropertyOverrides({
                                        m2NDNoCf5: {
                                            variant: "rML7zaR9u"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 1,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 225,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 201
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1fy21v5-container",
                                layoutDependency: layoutDependency,
                                layoutId: "eP4vx4Fo0-container",
                                nodeId: "eP4vx4Fo0",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(Divider, {
                                    fW4v8VMWk: "var(--token-9ae23472-2c52-4a18-9208-a0603db295c2, rgba(255, 255, 255, 0.08))",
                                    height: "100%",
                                    id: "eP4vx4Fo0",
                                    layoutId: "eP4vx4Fo0",
                                    style: {
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 76,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 250,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 218
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-2o6vn1-container",
                                layoutDependency: layoutDependency,
                                layoutId: "cKnSmyloT-container",
                                nodeId: "cKnSmyloT",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(TransactionRow, {
                                    FZkmj7Zu4: "lxcTGYbKP",
                                    height: "100%",
                                    id: "cKnSmyloT",
                                    kegb7UkZq: "+$2,800.00",
                                    layoutId: "cKnSmyloT",
                                    MNWfWU2ao: addImageAlt({
                                        pixelHeight: 40,
                                        pixelWidth: 40,
                                        src: "https://framerusercontent.com/images/PVryjSPlmTJ4XWqsuR2uGnQTQ.png"
                                    }, ""),
                                    nDbpvVAET: "Income",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "Br9c1tVCd",
                                    width: "100%",
                                    XFV53Cjx9: "May salary",
                                    zvO3HzvYM: "May 18",
                                    ...addPropertyOverrides({
                                        m2NDNoCf5: {
                                            variant: "rML7zaR9u"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 1,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 350,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 310
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-9ryd8k-container",
                                layoutDependency: layoutDependency,
                                layoutId: "lKPSQfPKu-container",
                                nodeId: "lKPSQfPKu",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(Divider, {
                                    fW4v8VMWk: "var(--token-9ae23472-2c52-4a18-9208-a0603db295c2, rgba(255, 255, 255, 0.08))",
                                    height: "100%",
                                    id: "lKPSQfPKu",
                                    layoutId: "lKPSQfPKu",
                                    style: {
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 76,
                            width: `max(${componentViewport?.width||"100vw"} - 388px, 1px)`,
                            y: (componentViewport ? .y || 0) + 48 + 0 + 375,
                            ...addPropertyOverrides({
                                m2NDNoCf5: {
                                    width: `calc(${componentViewport?.width||"100vw"} - 48px)`,
                                    y: (componentViewport ? .y || 0) + 24 + 162 + 0 + 327
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-i0kak7-container",
                                layoutDependency: layoutDependency,
                                layoutId: "Jxk8E8Sz5-container",
                                nodeId: "Jxk8E8Sz5",
                                rendersWithMotion: true,
                                scopeId: "zOrjBgUwU",
                                children: /*#__PURE__*/ _jsx(TransactionRow, {
                                    FZkmj7Zu4: "Ea6t1s6og",
                                    height: "100%",
                                    id: "Jxk8E8Sz5",
                                    kegb7UkZq: "-$7.80",
                                    layoutId: "Jxk8E8Sz5",
                                    MNWfWU2ao: addImageAlt({
                                        pixelHeight: 40,
                                        pixelWidth: 40,
                                        src: "https://framerusercontent.com/images/uRwwNrXLOSbXZFHekvm4GkT29MQ.png"
                                    }, ""),
                                    nDbpvVAET: "Entertainment",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "Br9c1tVCd",
                                    width: "100%",
                                    XFV53Cjx9: "Steam",
                                    zvO3HzvYM: "May 11",
                                    ...addPropertyOverrides({
                                        m2NDNoCf5: {
                                            variant: "rML7zaR9u"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-unIje.framer-k1rr3y, .framer-unIje .framer-k1rr3y { display: block; }", ".framer-unIje.framer-68izr1 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 448px; justify-content: flex-start; overflow: hidden; padding: 48px; position: relative; width: 872px; }", ".framer-unIje .framer-1vo8ve9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 244px; word-break: break-word; word-wrap: break-word; }", ".framer-unIje .framer-4znly9 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-unIje .framer-1p5z3an-container, .framer-unIje .framer-16kjcov-container, .framer-unIje .framer-vxg9l5-container, .framer-unIje .framer-1fy21v5-container, .framer-unIje .framer-2o6vn1-container, .framer-unIje .framer-9ryd8k-container, .framer-unIje .framer-i0kak7-container { flex: none; height: auto; position: relative; width: 100%; }", ".framer-unIje.framer-v-iwtn14.framer-68izr1 { flex-direction: column; gap: 24px; padding: 24px; width: 356px; }", ".framer-unIje.framer-v-iwtn14 .framer-1vo8ve9 { width: 162px; }", ".framer-unIje.framer-v-iwtn14 .framer-4znly9 { flex: none; gap: 16px; width: 100%; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 448
 * @framerIntrinsicWidth 872
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"m2NDNoCf5":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerzOrjBgUwU = withCSS(Component, css, "framer-unIje");
export default FramerzOrjBgUwU;
FramerzOrjBgUwU.displayName = "4 transaction list";
FramerzOrjBgUwU.defaultProps = {
    height: 448,
    width: 872
};
addPropertyControls(FramerzOrjBgUwU, {
    variant: {
        options: ["D7Zfd9aKU", "m2NDNoCf5"],
        optionTitles: ["Desktop/Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerzOrjBgUwU, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...TransactionRowFonts, ...DividerFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerzOrjBgUwU",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "872",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "448",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"m2NDNoCf5\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zOrjBgUwU.map