// Generated by Framer (629c622)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFonts,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Text from "https://framerusercontent.com/modules/4VerBjFLfFREcETAQ1hd/LyyvzhOEBA7KNYHwjnGv/jypRw1PbJ.js";
const TextFonts = getFonts(Text);
const cycleOrder = ["obVmnTQQJ", "IJpVqfjNm"];
const serializationHash = "framer-4DdmD";
const variantClassNames = {
    IJpVqfjNm: "framer-v-1qdfbnx",
    obVmnTQQJ: "framer-v-iwul4q"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Desktop/Tablet": "obVmnTQQJ",
    Phone: "IJpVqfjNm"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "obVmnTQQJ"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "obVmnTQQJ",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-iwul4q", className, classNames),
                    "data-framer-name": "Desktop/Tablet",
                    layoutDependency: layoutDependency,
                    layoutId: "obVmnTQQJ",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-ca7e2717-5e03-4734-9e61-71d320664250, rgb(243, 243, 243))",
                        borderBottomLeftRadius: 30,
                        borderBottomRightRadius: 30,
                        borderTopLeftRadius: 30,
                        borderTopRightRadius: 30,
                        ...style
                    },
                    variants: {
                        IJpVqfjNm: {
                            borderBottomLeftRadius: 25,
                            borderBottomRightRadius: 25,
                            borderTopLeftRadius: 25,
                            borderTopRightRadius: 25
                        }
                    },
                    ...addPropertyOverrides({
                        IJpVqfjNm: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "",
                            backgroundSize: 1.1,
                            fit: "tile",
                            intrinsicHeight: 16,
                            intrinsicWidth: 16,
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 0),
                            pixelHeight: 20,
                            pixelWidth: 20,
                            positionX: "center",
                            positionY: "center",
                            src: "https://framerusercontent.com/images/btMu5iFOvR85ltutCi07GNC0K6Y.png"
                        },
                        className: "framer-qfw1zd",
                        "data-framer-name": "bg dots",
                        layoutDependency: layoutDependency,
                        layoutId: "XNL8XTEg4",
                        style: {
                            opacity: .15
                        }
                    }), /*#__PURE__*/ _jsx(Text, {
                        animated: true,
                        className: "framer-1x6q3vh",
                        "data-framer-name": "logo",
                        layoutDependency: layoutDependency,
                        layoutId: "LhAhWqQNX",
                        name: "logo",
                        transformTemplate: transformTemplate1
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-4DdmD.framer-1fdcsq7, .framer-4DdmD .framer-1fdcsq7 { display: block; }", ".framer-4DdmD.framer-iwul4q { gap: 0px; height: 715px; overflow: hidden; position: relative; width: 300px; will-change: var(--framer-will-change-override, transform); }", ".framer-4DdmD .framer-qfw1zd { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-4DdmD .framer-1x6q3vh { flex: none; height: var(--framer-aspect-ratio-supported, 40px); left: 50%; position: absolute; top: 50%; width: 108px; }", ".framer-4DdmD.framer-v-1qdfbnx.framer-iwul4q { aspect-ratio: 0.4614457831325301 / 1; height: var(--framer-aspect-ratio-supported, 505px); width: 233px; }", ".framer-4DdmD.framer-v-1qdfbnx .framer-1x6q3vh { height: var(--framer-aspect-ratio-supported, 31px); width: 83px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 650
 * @framerIntrinsicWidth 300
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"IJpVqfjNm":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerVWx5UxYtR = withCSS(Component, css, "framer-4DdmD");
export default FramerVWx5UxYtR;
FramerVWx5UxYtR.displayName = "home-intro";
FramerVWx5UxYtR.defaultProps = {
    height: 650,
    width: 300
};
addPropertyControls(FramerVWx5UxYtR, {
    variant: {
        options: ["obVmnTQQJ", "IJpVqfjNm"],
        optionTitles: ["Desktop/Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerVWx5UxYtR, [{
    explicitInter: true,
    fonts: []
}, ...TextFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerVWx5UxYtR",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "650",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "300",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"IJpVqfjNm\":{\"layout\":[\"fixed\",\"fixed\"]}}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./VWx5UxYtR.map