// Generated by Framer (2797bee)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Tab from "https://framerusercontent.com/modules/oVagujpDNHC4lX8Nhd3K/MAdlcs8UZ7TjOmrKPThS/yyaoh3y14.js";
const TabFonts = getFonts(Tab);
const cycleOrder = ["l9gqu0VWr", "cxaP8loV7", "Th7C3WNkh"];
const serializationHash = "framer-Kj4fw";
const variantClassNames = {
    cxaP8loV7: "framer-v-1mmsgcx",
    l9gqu0VWr: "framer-v-guxpj3",
    Th7C3WNkh: "framer-v-dfqg50"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 48,
    delay: 0,
    mass: 1,
    stiffness: 340,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Tab 1 Hover": "l9gqu0VWr",
    "Tab 2 Hover": "cxaP8loV7",
    "Tab 3 Hover": "Th7C3WNkh"
};
const getProps = ({
    click1,
    click2,
    click3,
    description1,
    description2,
    description3,
    height,
    id,
    title1,
    title2,
    title3,
    width,
    ...props
}) => {
    return { ...props,
        aYKSajl0e: click1 ? ? props.aYKSajl0e,
        CBdqp0Qti: description2 ? ? props.CBdqp0Qti ? ? "Description",
        COrk9TzpT: title3 ? ? props.COrk9TzpT ? ? "Title",
        hM4VZyD_m: description1 ? ? props.hM4VZyD_m ? ? "Description",
        ihvn40UWn: click2 ? ? props.ihvn40UWn,
        n8KrsvZT8: click3 ? ? props.n8KrsvZT8,
        peEg9mG2F: title2 ? ? props.peEg9mG2F ? ? "Title",
        PonjRvYyZ: description3 ? ? props.PonjRvYyZ ? ? "Description",
        PRWhwbI_y: title1 ? ? props.PRWhwbI_y ? ? "Title",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "l9gqu0VWr"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        aYKSajl0e,
        ihvn40UWn,
        n8KrsvZT8,
        PRWhwbI_y,
        hM4VZyD_m,
        peEg9mG2F,
        CBdqp0Qti,
        COrk9TzpT,
        PonjRvYyZ,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "l9gqu0VWr",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const Hg1KMNEbl1vi912z = activeVariantCallback(async (...args) => {
        if (aYKSajl0e) {
            const res = await aYKSajl0e(...args);
            if (res === false) return false;
        }
    });
    const Hg1KMNEbl10atv0k = activeVariantCallback(async (...args) => {
        if (ihvn40UWn) {
            const res = await ihvn40UWn(...args);
            if (res === false) return false;
        }
    });
    const Hg1KMNEbl1kgyidi = activeVariantCallback(async (...args) => {
        if (n8KrsvZT8) {
            const res = await n8KrsvZT8(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-guxpj3", className, classNames),
                    "data-framer-name": "Tab 1 Hover",
                    layoutDependency: layoutDependency,
                    layoutId: "l9gqu0VWr",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        cxaP8loV7: {
                            "data-framer-name": "Tab 2 Hover"
                        },
                        Th7C3WNkh: {
                            "data-framer-name": "Tab 3 Hover"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 93,
                        width: `max((${componentViewport?.width||"100vw"} - 32px) / 3, 1px)`,
                        y: (componentViewport ? .y || 0) + 0,
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-259qmz-container",
                            layoutDependency: layoutDependency,
                            layoutId: "q8Rz7xIIw-container",
                            nodeId: "q8Rz7xIIw",
                            rendersWithMotion: true,
                            scopeId: "ObjEVqDN8",
                            children: /*#__PURE__*/ _jsx(Tab, {
                                height: "100%",
                                Hg1KMNEbl: Hg1KMNEbl1vi912z,
                                id: "q8Rz7xIIw",
                                layoutId: "q8Rz7xIIw",
                                OVaR3kyCn: hM4VZyD_m,
                                style: {
                                    width: "100%"
                                },
                                variant: "vBpbMYxf5",
                                width: "100%",
                                ZCPYk6gDj: PRWhwbI_y,
                                ...addPropertyOverrides({
                                    cxaP8loV7: {
                                        variant: "QroxpyI30"
                                    },
                                    Th7C3WNkh: {
                                        variant: "QroxpyI30"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 93,
                        width: `max((${componentViewport?.width||"100vw"} - 32px) / 3, 1px)`,
                        y: (componentViewport ? .y || 0) + 0,
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-10jq381-container",
                            layoutDependency: layoutDependency,
                            layoutId: "dW4kiq30K-container",
                            nodeId: "dW4kiq30K",
                            rendersWithMotion: true,
                            scopeId: "ObjEVqDN8",
                            children: /*#__PURE__*/ _jsx(Tab, {
                                height: "100%",
                                Hg1KMNEbl: Hg1KMNEbl10atv0k,
                                id: "dW4kiq30K",
                                layoutId: "dW4kiq30K",
                                OVaR3kyCn: CBdqp0Qti,
                                style: {
                                    width: "100%"
                                },
                                variant: "QroxpyI30",
                                width: "100%",
                                ZCPYk6gDj: peEg9mG2F,
                                ...addPropertyOverrides({
                                    cxaP8loV7: {
                                        variant: "vBpbMYxf5"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 93,
                        width: `max((${componentViewport?.width||"100vw"} - 32px) / 3, 1px)`,
                        y: (componentViewport ? .y || 0) + 0,
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1du22c4-container",
                            layoutDependency: layoutDependency,
                            layoutId: "JA3Gy3RR9-container",
                            nodeId: "JA3Gy3RR9",
                            rendersWithMotion: true,
                            scopeId: "ObjEVqDN8",
                            children: /*#__PURE__*/ _jsx(Tab, {
                                height: "100%",
                                Hg1KMNEbl: Hg1KMNEbl1kgyidi,
                                id: "JA3Gy3RR9",
                                layoutId: "JA3Gy3RR9",
                                OVaR3kyCn: PonjRvYyZ,
                                style: {
                                    width: "100%"
                                },
                                variant: "QroxpyI30",
                                width: "100%",
                                ZCPYk6gDj: COrk9TzpT,
                                ...addPropertyOverrides({
                                    Th7C3WNkh: {
                                        variant: "vBpbMYxf5"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1l1es13",
                        "data-framer-name": "highlight",
                        layoutDependency: layoutDependency,
                        layoutId: "hFphoSJiH",
                        style: {
                            backgroundColor: "var(--token-a5496d0e-d29d-467d-997c-173a5ba2d4ab, rgba(255, 255, 255, 0.12))",
                            borderBottomLeftRadius: 12,
                            borderBottomRightRadius: 12,
                            borderTopLeftRadius: 12,
                            borderTopRightRadius: 12
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Kj4fw.framer-l9jy7h, .framer-Kj4fw .framer-l9jy7h { display: block; }", ".framer-Kj4fw.framer-guxpj3 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 872px; }", ".framer-Kj4fw .framer-259qmz-container, .framer-Kj4fw .framer-10jq381-container, .framer-Kj4fw .framer-1du22c4-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; z-index: 2; }", ".framer-Kj4fw .framer-1l1es13 { flex: none; height: 100%; left: 0px; overflow: hidden; position: absolute; top: 0px; width: 32%; will-change: var(--framer-will-change-override, transform); z-index: 0; }", ".framer-Kj4fw.framer-v-1mmsgcx .framer-1l1es13 { left: calc(50.00000000000002% - 32.22477064220183% / 2); }", ".framer-Kj4fw.framer-v-dfqg50 .framer-1l1es13 { left: unset; right: 0px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 93.5
 * @framerIntrinsicWidth 872
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"cxaP8loV7":{"layout":["fixed","auto"]},"Th7C3WNkh":{"layout":["fixed","auto"]}}}
 * @framerVariables {"aYKSajl0e":"click1","ihvn40UWn":"click2","n8KrsvZT8":"click3","PRWhwbI_y":"title1","hM4VZyD_m":"description1","peEg9mG2F":"title2","CBdqp0Qti":"description2","COrk9TzpT":"title3","PonjRvYyZ":"description3"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerObjEVqDN8 = withCSS(Component, css, "framer-Kj4fw");
export default FramerObjEVqDN8;
FramerObjEVqDN8.displayName = "3 desktop tab wrap";
FramerObjEVqDN8.defaultProps = {
    height: 93.5,
    width: 872
};
addPropertyControls(FramerObjEVqDN8, {
    variant: {
        options: ["l9gqu0VWr", "cxaP8loV7", "Th7C3WNkh"],
        optionTitles: ["Tab 1 Hover", "Tab 2 Hover", "Tab 3 Hover"],
        title: "Variant",
        type: ControlType.Enum
    },
    aYKSajl0e: {
        title: "Click 1",
        type: ControlType.EventHandler
    },
    ihvn40UWn: {
        title: "Click 2",
        type: ControlType.EventHandler
    },
    n8KrsvZT8: {
        title: "Click 3",
        type: ControlType.EventHandler
    },
    PRWhwbI_y: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title 1",
        type: ControlType.String
    },
    hM4VZyD_m: {
        defaultValue: "Description",
        displayTextArea: true,
        title: "Description 1",
        type: ControlType.String
    },
    peEg9mG2F: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title 2",
        type: ControlType.String
    },
    CBdqp0Qti: {
        defaultValue: "Description",
        displayTextArea: true,
        title: "Description 2",
        type: ControlType.String
    },
    COrk9TzpT: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title 3",
        type: ControlType.String
    },
    PonjRvYyZ: {
        defaultValue: "Description",
        displayTextArea: true,
        title: "Description 3",
        type: ControlType.String
    }
});
addFonts(FramerObjEVqDN8, [{
    explicitInter: true,
    fonts: []
}, ...TabFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerObjEVqDN8",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "872",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerVariables": "{\"aYKSajl0e\":\"click1\",\"ihvn40UWn\":\"click2\",\"n8KrsvZT8\":\"click3\",\"PRWhwbI_y\":\"title1\",\"hM4VZyD_m\":\"description1\",\"peEg9mG2F\":\"title2\",\"CBdqp0Qti\":\"description2\",\"COrk9TzpT\":\"title3\",\"PonjRvYyZ\":\"description3\"}",
                "framerIntrinsicHeight": "93.5",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"cxaP8loV7\":{\"layout\":[\"fixed\",\"auto\"]},\"Th7C3WNkh\":{\"layout\":[\"fixed\",\"auto\"]}}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ObjEVqDN8.map