// Generated by Framer (6b58135)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/rtyUqULPxEEGfMf676iN/Ygr7BcGnPs23VkHvmm3S/IT3UYlzmK.js";
const serializationHash = "framer-CvX9s";
const variantClassNames = {
    vJCy2zE_T: "framer-v-462z2w"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    text,
    width,
    ...props
}) => {
    return { ...props,
        wamczWuh8: text ? ? props.wamczWuh8 ? ? "Text"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        wamczWuh8,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "vJCy2zE_T",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-462z2w", className, classNames),
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "vJCy2zE_T",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-gzvryk",
                        "data-framer-name": "dot",
                        layoutDependency: layoutDependency,
                        layoutId: "KDhxWOXQY",
                        style: {
                            backgroundColor: "var(--token-8e327549-68cc-4529-a405-c79194616058, rgb(27, 43, 184))",
                            borderBottomLeftRadius: "100%",
                            borderBottomRightRadius: "100%",
                            borderTopLeftRadius: "100%",
                            borderTopRightRadius: "100%"
                        }
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-5r7f4r",
                                "data-styles-preset": "IT3UYlzmK",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-1e23e8ab-09bc-463f-a722-5892dbae21bf, rgba(0, 0, 0, 0.6)))"
                                },
                                children: "Our history"
                            })
                        }),
                        className: "framer-12cfjc5",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "dAOsYZHpR",
                        style: {
                            "--extracted-r6o4lv": "var(--token-1e23e8ab-09bc-463f-a722-5892dbae21bf, rgba(0, 0, 0, 0.6))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: wamczWuh8,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-CvX9s.framer-hm0kwb, .framer-CvX9s .framer-hm0kwb { display: block; }", ".framer-CvX9s.framer-462z2w { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }", ".framer-CvX9s .framer-gzvryk { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 6px); overflow: hidden; position: relative; width: 6px; will-change: var(--framer-will-change-override, transform); }", ".framer-CvX9s .framer-12cfjc5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 13
 * @framerIntrinsicWidth 45
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"wamczWuh8":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerI7HOnbC8q = withCSS(Component, css, "framer-CvX9s");
export default FramerI7HOnbC8q;
FramerI7HOnbC8q.displayName = "section label";
FramerI7HOnbC8q.defaultProps = {
    height: 13,
    width: 45
};
addPropertyControls(FramerI7HOnbC8q, {
    wamczWuh8: {
        defaultValue: "Text",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    }
});
addFonts(FramerI7HOnbC8q, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerI7HOnbC8q",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"wamczWuh8\":\"text\"}",
                "framerIntrinsicWidth": "45",
                "framerIntrinsicHeight": "13",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./I7HOnbC8q.map