// Generated by Framer (ac3cb42)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: fill ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-HPtvn", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--21h8s6": ezTt3ayMo,
            ...style
        }
    });
});
const css = ['.framer-HPtvn { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url(\'data:image/svg+xml,<svg aria-label="Magnifying Glass" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 19.301 18.24 L 14.607 13.547 C 17.434 10.154 17.091 5.138 13.83 2.16 C 10.569 -0.818 5.542 -0.703 2.419 2.419 C -0.703 5.542 -0.818 10.569 2.16 13.83 C 5.138 17.091 10.154 17.434 13.547 14.607 L 18.24 19.301 C 18.533 19.594 19.008 19.594 19.301 19.301 C 19.594 19.008 19.594 18.533 19.301 18.24 Z M 1.521 8.271 C 1.521 4.543 4.543 1.521 8.271 1.521 C 11.999 1.521 15.021 4.543 15.021 8.271 C 15.021 11.999 11.999 15.021 8.271 15.021 C 4.545 15.017 1.525 11.997 1.521 8.271 Z" fill="var(--21h8s6, rgb(0,0,0))" height="19.521148357002613px" id="wF_eq6oUM" opacity="1" transform="translate(2.229 2.229)" width="19.52114835700349px"/></svg>\'); mask-position: center; mask-repeat: no-repeat; width: 24px; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"fill"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Magnifying Glass","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-HPtvn");
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "24",
                "framerVariables": "{\"ezTt3ayMo\":\"fill\"}",
                "framerIntrinsicHeight": "24",
                "framerDisableUnlink": "true",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerVector": "{\"name\":\"Magnifying Glass\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}