// Generated by Framer (5012657)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import AnimatedNumberCounter from "https://framerusercontent.com/modules/qpjhCcDm4G1NbFAlpMKV/OnyZiTlIjOBuSKcKQWFv/AnimatedNumberCounter_Prod.js";
const AnimatedNumberCounterFonts = getFonts(AnimatedNumberCounter);
const cycleOrder = ["FHsDbxyvG", "MbncyYu4f"];
const serializationHash = "framer-tqQSX";
const variantClassNames = {
    FHsDbxyvG: "framer-v-1f9gdqf",
    MbncyYu4f: "framer-v-mwjcbu"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    End: "MbncyYu4f",
    Start: "FHsDbxyvG"
};
const getProps = ({
    end,
    height,
    id,
    start,
    width,
    ...props
}) => {
    return { ...props,
        I2dRXA8zx: start ? ? props.I2dRXA8zx,
        LCWLRTgaQ: end ? ? props.LCWLRTgaQ ? ? 568.67,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "FHsDbxyvG"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        I2dRXA8zx,
        LCWLRTgaQ,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "FHsDbxyvG",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1f9gdqf", className, classNames),
                    "data-framer-name": "Start",
                    layoutDependency: layoutDependency,
                    layoutId: "FHsDbxyvG",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        MbncyYu4f: {
                            "data-framer-name": "End"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1f75dbn-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "j9103ozHq-container",
                            nodeId: "j9103ozHq",
                            rendersWithMotion: true,
                            scopeId: "zZlvxle6C",
                            children: /*#__PURE__*/ _jsx(AnimatedNumberCounter, {
                                animation: {
                                    replay: true,
                                    transition: {
                                        bounce: 0,
                                        delay: 0,
                                        duration: 1,
                                        type: "spring"
                                    },
                                    trigger: "layerInView"
                                },
                                balance: false,
                                color: {
                                    angle: 180,
                                    color: "var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, rgb(0, 0, 0))",
                                    endColor: "rgb(255, 255, 255)",
                                    mode: "solid",
                                    startColor: "rgb(0, 0, 0)"
                                },
                                commas: true,
                                decimals: 2,
                                decoration: "none",
                                end: 100,
                                font: {
                                    fontFamily: '"General Sans", "General Sans Placeholder", sans-serif',
                                    fontFeatureSettings: "'zero' on, 'tnum' on",
                                    fontSize: "42px",
                                    fontStyle: "normal",
                                    fontWeight: 500,
                                    letterSpacing: "-0.03em",
                                    lineHeight: "110%"
                                },
                                height: "100%",
                                id: "j9103ozHq",
                                layoutId: "j9103ozHq",
                                mode: "variants",
                                monospace: false,
                                prefix: "$",
                                start: 0,
                                suffix: "",
                                tag: "p",
                                transition: {
                                    bounce: 0,
                                    delay: 0,
                                    duration: 1.5,
                                    type: "spring"
                                },
                                userSelect: true,
                                value: I2dRXA8zx,
                                width: "100%",
                                ...addPropertyOverrides({
                                    MbncyYu4f: {
                                        value: LCWLRTgaQ
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-tqQSX.framer-1d9bho9, .framer-tqQSX .framer-1d9bho9 { display: block; }", ".framer-tqQSX.framer-1f9gdqf { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 142px; }", ".framer-tqQSX .framer-1f75dbn-container { flex: none; height: auto; position: relative; width: auto; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 46
 * @framerIntrinsicWidth 142
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"MbncyYu4f":{"layout":["fixed","auto"]}}}
 * @framerVariables {"I2dRXA8zx":"start","LCWLRTgaQ":"end"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerzZlvxle6C = withCSS(Component, css, "framer-tqQSX");
export default FramerzZlvxle6C;
FramerzZlvxle6C.displayName = "section-hero/number counter";
FramerzZlvxle6C.defaultProps = {
    height: 46,
    width: 142
};
addPropertyControls(FramerzZlvxle6C, {
    variant: {
        options: ["FHsDbxyvG", "MbncyYu4f"],
        optionTitles: ["Start", "End"],
        title: "Variant",
        type: ControlType.Enum
    },
    I2dRXA8zx: {
        defaultValue: 0,
        title: "Start",
        type: ControlType.Number
    },
    LCWLRTgaQ: {
        defaultValue: 568.67,
        title: "End",
        type: ControlType.Number
    }
});
addFonts(FramerzZlvxle6C, [{
    explicitInter: true,
    fonts: [{
        family: "General Sans",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/3RZHWSNONLLWJK3RLPEKUZOMM56GO4LJ/BPDRY7AHVI3MCDXXVXTQQ76H3UXA63S3/SB2OEB6IKZPRR6JT4GFJ2TFT6HBB6AZN.woff2",
        weight: "500"
    }]
}, ...AnimatedNumberCounterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerzZlvxle6C",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "142",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "46",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"MbncyYu4f\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"I2dRXA8zx\":\"start\",\"LCWLRTgaQ\":\"end\"}",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zZlvxle6C.map