// Generated by Framer (ac3cb42)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: fill ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-8d8yn", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--21h8s6": ezTt3ayMo,
            ...style
        }
    });
});
const css = ['.framer-8d8yn { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url(\'data:image/svg+xml,<svg aria-label="Arrows Counter Clockwise" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 5.25 6.568 L 0.75 6.568 C 0.336 6.568 0 6.232 0 5.818 L 0 1.318 C 0 0.904 0.336 0.568 0.75 0.568 C 1.164 0.568 1.5 0.904 1.5 1.318 L 1.5 4.008 L 2.872 2.636 C 4.544 0.955 6.816 0.007 9.188 0 L 9.237 0 C 11.589 -0.006 13.848 0.915 15.525 2.562 C 15.81 2.854 15.81 3.319 15.525 3.611 C 15.24 3.902 14.775 3.913 14.477 3.635 C 13.079 2.262 11.196 1.495 9.237 1.5 L 9.195 1.5 C 7.219 1.506 5.326 2.296 3.932 3.697 L 2.56 5.068 L 5.25 5.068 C 5.664 5.068 6 5.404 6 5.818 C 6 6.232 5.664 6.568 5.25 6.568 Z M 17.25 11.068 L 12.75 11.068 C 12.336 11.068 12 11.404 12 11.818 C 12 12.232 12.336 12.568 12.75 12.568 L 15.44 12.568 L 14.068 13.94 C 12.674 15.34 10.782 16.13 8.806 16.136 L 8.764 16.136 C 6.805 16.141 4.922 15.374 3.524 14.002 C 3.334 13.807 3.053 13.731 2.791 13.802 C 2.528 13.874 2.325 14.082 2.26 14.346 C 2.194 14.61 2.277 14.888 2.476 15.074 C 4.153 16.722 6.412 17.642 8.764 17.636 L 8.813 17.636 C 11.184 17.629 13.455 16.681 15.128 15 L 16.5 13.628 L 16.5 16.318 C 16.5 16.732 16.836 17.068 17.25 17.068 C 17.664 17.068 18 16.732 18 16.318 L 18 11.818 C 18 11.404 17.664 11.068 17.25 11.068 Z" fill="var(--21h8s6, rgb(0,0,0))" height="17.636309042110163px" id="s01eRZUhb" opacity="1" transform="translate(3 3.182)" width="18.000000359358353px"/></svg>\'); mask-position: center; mask-repeat: no-repeat; width: 24px; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"fill"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Arrows Counter Clockwise","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-8d8yn");
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"ezTt3ayMo\":\"fill\"}",
                "framerDisableUnlink": "true",
                "framerIntrinsicHeight": "24",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Arrows Counter Clockwise\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "24",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}