// Generated by Framer (2797bee)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    ResolveLinks,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useRouter,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/sVaDCHlzoAwFe2FWWQvP/nzFJoVYOuJsa8rodMZf7/GfcsZ4rRT.js";
import Primary from "https://framerusercontent.com/modules/8AZqOIiwAp7LBu9Q7SuK/8qIvNShA0vPq3n911q3k/NoImOvSr5.js";
const PrimaryFonts = getFonts(Primary);
const cycleOrder = ["mtKNnhxE8", "FahbTETHx", "Yvo9S8Oj9"];
const serializationHash = "framer-l2EZU";
const variantClassNames = {
    FahbTETHx: "framer-v-11im274",
    mtKNnhxE8: "framer-v-11k29ma",
    Yvo9S8Oj9: "framer-v-bjl101"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "mtKNnhxE8",
    Phone: "Yvo9S8Oj9",
    Tablet: "FahbTETHx"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "mtKNnhxE8"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "mtKNnhxE8",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const router = useRouter();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.section, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-11k29ma", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "mtKNnhxE8",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        FahbTETHx: {
                            "data-framer-name": "Tablet"
                        },
                        Yvo9S8Oj9: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-16qc177",
                        "data-framer-name": "max-width",
                        layoutDependency: layoutDependency,
                        layoutId: "T1qAUw_Yz",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                    className: "framer-styles-preset-4kq9mo",
                                    "data-styles-preset": "GfcsZ4rRT",
                                    style: {
                                        "--framer-text-alignment": "left",
                                        "--framer-text-color": "var(--extracted-1of0zx5, var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, rgb(0, 0, 0)))"
                                    },
                                    children: "Use Nova to track smarter, save better, and make every dollar work for you."
                                })
                            }),
                            className: "framer-npa8w8",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "QsG1DO5w1",
                            style: {
                                "--extracted-1of0zx5": "var(--token-ded86de6-1b9d-4d9f-87d2-a30c6b424700, rgb(0, 0, 0))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [{
                                href: {
                                    hash: ":g6esfW4YW",
                                    webPageId: "augiA20Il"
                                },
                                implicitPathVariables: undefined
                            }, {
                                href: {
                                    hash: ":g6esfW4YW",
                                    webPageId: "augiA20Il"
                                },
                                implicitPathVariables: undefined
                            }, {
                                href: {
                                    hash: ":g6esfW4YW",
                                    webPageId: "augiA20Il"
                                },
                                implicitPathVariables: undefined
                            }],
                            children: resolvedLinks => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 52,
                                y: (componentViewport ? .y || 0) + 164 + 0 + 0 + 96.8,
                                ...addPropertyOverrides({
                                    Yvo9S8Oj9: {
                                        y: (componentViewport ? .y || 0) + 64 + 0 + 0 + 88.8
                                    }
                                }, baseVariant, gestureVariant),
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-35rb3z-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "Jgfs09C75-container",
                                    nodeId: "Jgfs09C75",
                                    rendersWithMotion: true,
                                    scopeId: "SORTCkIvs",
                                    children: /*#__PURE__*/ _jsx(Primary, {
                                        height: "100%",
                                        id: "Jgfs09C75",
                                        layoutId: "Jgfs09C75",
                                        oJbsFmf1j: "Start tracking for free",
                                        PTAwKYYxn: resolvedLinks[0],
                                        sl1qukewy: true,
                                        style: {
                                            height: "100%"
                                        },
                                        variant: "Hzpw7va8p",
                                        width: "100%",
                                        ...addPropertyOverrides({
                                            FahbTETHx: {
                                                PTAwKYYxn: resolvedLinks[1]
                                            },
                                            Yvo9S8Oj9: {
                                                PTAwKYYxn: resolvedLinks[2]
                                            }
                                        }, baseVariant, gestureVariant)
                                    })
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-l2EZU.framer-1eaurl5, .framer-l2EZU .framer-1eaurl5 { display: block; }", ".framer-l2EZU.framer-11k29ma { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 112px; height: min-content; justify-content: flex-start; overflow: visible; padding: 164px 0px 164px 0px; position: relative; width: 1200px; }", ".framer-l2EZU .framer-16qc177 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 44px; height: min-content; justify-content: flex-start; max-width: 872px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }", ".framer-l2EZU .framer-npa8w8 { flex: none; height: auto; max-width: 644px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-l2EZU .framer-35rb3z-container { flex: none; height: 52px; position: relative; width: auto; }", ".framer-l2EZU.framer-v-11im274.framer-11k29ma { padding: 164px 36px 164px 36px; width: 810px; }", ".framer-l2EZU.framer-v-bjl101.framer-11k29ma { gap: 64px; padding: 64px 20px 64px 20px; width: 390px; }", ".framer-l2EZU.framer-v-bjl101 .framer-16qc177 { gap: 36px; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 582.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"FahbTETHx":{"layout":["fixed","auto"]},"Yvo9S8Oj9":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerSORTCkIvs = withCSS(Component, css, "framer-l2EZU");
export default FramerSORTCkIvs;
FramerSORTCkIvs.displayName = "main component";
FramerSORTCkIvs.defaultProps = {
    height: 582.5,
    width: 1200
};
addPropertyControls(FramerSORTCkIvs, {
    variant: {
        options: ["mtKNnhxE8", "FahbTETHx", "Yvo9S8Oj9"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerSORTCkIvs, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PrimaryFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerSORTCkIvs",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"FahbTETHx\":{\"layout\":[\"fixed\",\"auto\"]},\"Yvo9S8Oj9\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "582.5",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "1200",
                "framerAutoSizeImages": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./SORTCkIvs.map